FROM nginx:alpine
COPY docker-entrypoint.sh /docker-entrypoint2.sh
RUN sed -i 's/\r$//' /docker-entrypoint2.sh
COPY nginx.conf.template /
COPY apps/web/build /usr/share/nginx/html
RUN chmod -R a+r /usr/share/nginx/html
ENTRYPOINT ["sh", "/docker-entrypoint2.sh"]
CMD ["nginx","-g","daemon off;"]
