import { ChannelTypeGroup, ChannelTypePerson } from "wukongimjssdk";
import type { DocumentState } from "./types";

export const initialDocumentState: DocumentState = {
  spaces: [
    {
      id: "space-east-delivery",
      name: "华东交付部空间",
      fileCount: 1,
      memberCount: 42,
      description: "客户交付材料、项目计划和现场实施记录",
    },
    {
      id: "space-product",
      name: "产品部公共空间",
      fileCount: 1,
      memberCount: 18,
      description: "需求清单、评审材料和共享说明",
    },
    {
      id: "space-product-archive",
      name: "产品归档空间",
      fileCount: 0,
      memberCount: 18,
      description: "产品团队长期保存的会话文件",
    },
    {
      id: "space-policy",
      name: "公司制度空间",
      fileCount: 1,
      memberCount: 326,
      description: "公司级正式制度、公告和版本记录",
    },
  ],
  files: [
    {
      id: "DOC-240617-001",
      name: "仅张沐可见-客户现场实施计划.pdf",
      kind: "pdf",
      extension: "pdf",
      size: 18_400_000,
      url: "/mock-files/q3-delivery-plan.pdf",
      owner: "张沐",
      uploader: "张沐",
      uploaderUid: "u-zhangmu",
      sourceName: "华东项目交付群",
      sourceChannelId: "group-east-delivery",
      sourceChannelType: ChannelTypeGroup,
      sourceType: "group",
      sourceMessageId: "MSG-240612-001",
      sourceMessageSeq: 3896,
      sourceSenderUid: "u-zhangmu",
      sourceSenderName: "张沐",
      sourceSentAt: "2026-06-12 09:42",
      sourcePreviewText: "这是 Q3 客户现场实施计划，请大家看下时间安排。",
      spaceName: "华东交付部空间",
      visibility: "space",
      status: "archived",
      createdAt: "2026-06-12 09:42",
      lastAccessAt: "2026-06-17 09:18",
      downloads: 42,
      previewable: true,
      flow: ["来自华东项目交付群", "保存到华东交付部空间"],
      access: {
        userUids: ["u-zhangmu"],
        channelIds: ["group-east-delivery"],
        spaceNames: ["华东交付部空间"],
      },
    },
    {
      id: "DOC-240617-002",
      name: "Octo 文件空间需求清单.xlsx",
      kind: "sheet",
      extension: "xlsx",
      size: 2_100_000,
      url: "/mock-files/octo-file-space.xlsx",
      owner: "陈一",
      uploader: "陈一",
      uploaderUid: "u-chenyi",
      sourceName: "产品方案讨论群",
      sourceChannelId: "group-product-plan",
      sourceChannelType: ChannelTypeGroup,
      sourceType: "group",
      sourceMessageId: "MSG-240615-002",
      sourceMessageSeq: 4208,
      sourceSenderUid: "u-chenyi",
      sourceSenderName: "陈一",
      sourceSentAt: "2026-06-15 15:26",
      sourcePreviewText: "我把文件空间需求清单放在这里，后面从会话文件入口管理。",
      spaceName: "产品部公共空间",
      visibility: "space",
      status: "archived",
      createdAt: "2026-06-15 15:26",
      lastAccessAt: "2026-06-17 10:02",
      downloads: 18,
      previewable: true,
      flow: ["来自产品方案讨论群", "保存到产品部公共空间"],
      access: {
        userUids: ["u-chenyi"],
        channelIds: ["group-product-plan"],
        spaceNames: ["产品部公共空间"],
      },
    },
    {
      id: "DOC-240617-003",
      name: "客户账号权限确认截图.png",
      kind: "image",
      extension: "png",
      size: 820_000,
      url: "/mock-files/account-confirm.png",
      owner: "李维",
      uploader: "李维",
      uploaderUid: "u-liwei",
      sourceName: "李维 / 韩霄 单聊",
      sourceChannelId: "u-liwei",
      sourceChannelType: ChannelTypePerson,
      sourceType: "direct",
      sourceMessageId: "MSG-240616-003",
      sourceMessageSeq: 175,
      sourceSenderUid: "u-liwei",
      sourceSenderName: "李维",
      sourceSentAt: "2026-06-16 11:03",
      sourcePreviewText: "这是客户账号的确认截图。",
      spaceName: "会话文件",
      visibility: "conversation",
      status: "conversation",
      createdAt: "2026-06-16 11:03",
      lastAccessAt: "2026-06-16 11:10",
      downloads: 3,
      previewable: true,
      flow: ["来自李维 / 韩霄 单聊", "保留在会话文件"],
      access: {
        userUids: ["u-chenyi", "u-liwei"],
        channelIds: ["u-liwei"],
      },
    },
    {
      id: "DOC-240617-004",
      name: "人力材料说明.zip",
      kind: "zip",
      extension: "zip",
      size: 76_900_000,
      url: "/mock-files/hr-materials.zip",
      owner: "张沐",
      uploader: "张沐",
      uploaderUid: "u-zhangmu",
      sourceName: "人力运营群",
      sourceChannelId: "group-hr-ops",
      sourceChannelType: ChannelTypeGroup,
      sourceType: "group",
      sourceMessageId: "MSG-240610-004",
      sourceMessageSeq: 981,
      sourceSenderUid: "u-zhangmu",
      sourceSenderName: "张沐",
      sourceSentAt: "2026-06-10 18:21",
      sourcePreviewText: "人力材料说明已整理好。",
      spaceName: "会话文件",
      visibility: "conversation",
      status: "conversation",
      createdAt: "2026-06-10 18:21",
      lastAccessAt: "2026-06-14 08:34",
      downloads: 7,
      previewable: false,
      flow: ["来自人力运营群", "保留在会话文件"],
      access: {
        userUids: ["u-zhangmu"],
        channelIds: ["group-hr-ops"],
      },
    },
    {
      id: "DOC-240617-005",
      name: "制度更新说明.docx",
      kind: "doc",
      extension: "docx",
      size: 1_600_000,
      url: "/mock-files/policy-update.docx",
      owner: "周岚",
      uploader: "周岚",
      uploaderUid: "u-zhoulan",
      sourceName: "行政制度发布群",
      sourceChannelId: "group-policy",
      sourceChannelType: ChannelTypeGroup,
      sourceType: "group",
      sourceMessageId: "MSG-240601-005",
      sourceMessageSeq: 2188,
      sourceSenderUid: "u-zhoulan",
      sourceSenderName: "周岚",
      sourceSentAt: "2026-06-01 10:05",
      sourcePreviewText: "制度更新说明请查收。",
      spaceName: "公司制度空间",
      visibility: "space",
      status: "deleted",
      createdAt: "2026-06-01 10:05",
      lastAccessAt: "2026-06-05 16:32",
      downloads: 25,
      previewable: true,
      flow: ["来自行政制度发布群", "保存到公司制度空间", "移到回收站"],
      access: {
        userUids: ["u-zhoulan"],
        channelIds: ["group-policy"],
        spaceNames: ["公司制度空间"],
      },
    },
  ],
};
